apiVersion: apps/v1
kind: Deployment	
metadata:
  name: rti-routingservice
spec:
  selector:
    matchLabels:
      app: rti-routingservice
  replicas: 2
  template:
    metadata:
      labels:
        app: rti-routingservice
    spec:
      containers:
      - name: rti-routingservice
        image: kyoungho/rti-routingservice:6.1.0
        ports:
        - containerPort: 7400
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.xml
          subPath: config.xml
        env:
        - name: CFG_NAME
          value: "RS-RWT"
        - name: ARGS
          value: "-verbosity 5"
        - name: PUBLIC_IP # value for public ip address
          value: "3.128.85.163"
        - name: PUBLIC_PORT # value for public port
          value: "7400"
        - name: HOST_PORT # value for host port 
          value: "7400"
        - name: WAN_DOMAIN # value for WAN domain ID
          value: "100"
        - name: LAN_DOMAIN # value for LAN domain ID
          value: "10"
      imagePullSecrets:
        - name: regcred
      volumes: 
        - name: config-volume
          configMap:
            name: routingservice-rwt
